-- MySQL Script generated by MySQL Workbench
-- Sun Apr 24 08:21:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema komision
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema komision
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `komision` DEFAULT CHARACTER SET utf8 ;
USE `komision` ;

-- -----------------------------------------------------
-- Table `komision`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komision`.`user` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `userID_UNIQUE` ON `komision`.`user` (`userID` ASC) VISIBLE;

CREATE UNIQUE INDEX `userName_UNIQUE` ON `komision`.`user` (`userName` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `komision`.`mod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komision`.`mod` (
  `modID` INT NOT NULL AUTO_INCREMENT,
  `modName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`modID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `userID_UNIQUE` ON `komision`.`mod` (`modID` ASC) VISIBLE;

CREATE UNIQUE INDEX `userName_UNIQUE` ON `komision`.`mod` (`modName` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `komision`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komision`.`chat` (
  `chatID` INT NOT NULL AUTO_INCREMENT,
  `chatMessage` LONGTEXT NULL,
  `userID` INT NOT NULL,
  `modID` INT NOT NULL,
  `creatde_at` DATETIME NULL DEFAULT CURRENT_TIMEPSTAMP,
  PRIMARY KEY (`chatID`),
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `komision`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `modID`
    FOREIGN KEY (`modID`)
    REFERENCES `komision`.`mod` (`modID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `chatID_UNIQUE` ON `komision`.`chat` (`chatID` ASC) VISIBLE;

CREATE INDEX `userID_idx` ON `komision`.`chat` (`userID` ASC) VISIBLE;

CREATE INDEX `modID_idx` ON `komision`.`chat` (`modID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `komision`.`commission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `komision`.`commission` (
  `commID` INT NOT NULL AUTO_INCREMENT,
  `chatID` INT NOT NULL,
  `userID` INT NOT NULL,
  `modID` INT NOT NULL,
  `creatde_at` DATETIME NULL DEFAULT CURRENT_TIMEPSTAMP,
  PRIMARY KEY (`commID`),
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `komision`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `modID`
    FOREIGN KEY (`modID`)
    REFERENCES `komision`.`mod` (`modID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chatID`
    FOREIGN KEY (`chatID`)
    REFERENCES `komision`.`chat` (`chatID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `chatID_UNIQUE` ON `komision`.`commission` (`commID` ASC) VISIBLE;

CREATE INDEX `userID_idx` ON `komision`.`commission` (`userID` ASC) VISIBLE;

CREATE INDEX `chatID_idx` ON `komision`.`commission` (`chatID` ASC) VISIBLE;

CREATE INDEX `modID_idx` ON `komision`.`commission` (`modID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
