insert into soda.specialties_list (spec_id, spec_desc, spec_name)
values  (1, null, 'Allergy and immunology'),
        (2, null, 'Anesthesiology'),
        (3, null, 'Cardiology'),
        (4, null, 'Cardiothoracic surgery'),
        (5, null, 'Psychiatry'),
        (6, null, 'Neurology'),
        (7, null, 'Dermatology'),
        (8, null, 'Pediatrics'),
        (9, null, 'Endocrinology'),
        (10, null, 'Gastroenterology'),
        (11, null, 'General surgery'),
        (12, null, 'Hematology'),
        (13, null, 'Internal medicine'),
        (14, null, 'Medical biochemistry'),
        (15, null, 'Nephrology'),
        (16, null, 'Neurology'),
        (17, null, 'Obstetrics and gynecology'),
        (18, null, 'Ophthalmology'),
        (19, null, 'Orthopedic surgery'),
        (20, null, 'Otorhinolaryngology'),
        (21, null, 'Psychiatry'),
        (22, null, 'Radiology'),
        (23, null, 'Rheumatology'),
        (24, null, 'Toxicology'),
        (25, null, 'Urology');